name: Build wireguard-go for Padavan

on: 
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 初始化
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        wget -O /tmp/golang.tar.gz https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
        sudo tar -C /usr/local -xvzf /tmp/golang.tar.gz
        export PATH=$PATH:/usr/local/go/bin
    - name: 编译wireguard-go
      run: |
        mkdir -p /tmp/gobuild/ && cd /tmp/gobuild/
        git clone https://git.zx2c4.com/wireguard-go
        cd wireguard-go
        export GOPATH="/tmp/gobuild/"
        env GOOS=linux GOARCH=mipsle go build -v -o "wireguard-go"
